### ISSUE TITLE
SObjectModel::Rest::RequestError 他、例外が出ても、コマンド内で補足してメッセージ表示していない

### ISSUE THREAD

**Issue by tmkw** [tmkw/alet#111]
```
> desc TestCustomObject__c -r
/home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/sobjectmodel-0.1.3/lib/sobject_model/rest/http.rb:24:in `get': []  (SObjectModel::Rest::RequestError)
	from /home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/sobjectmodel-0.1.3/lib/sobject_model/rest/client.rb:28:in `describe'
	from /home/cul8er/projects/alet/0.2.0/describe/lib/alet.rb:21:in `describe'
	from <internal:kernel>:187:in `loop'
	from /home/cul8er/projects/alet/0.2.0/describe/lib/alet/app.rb:43:in `block (2 levels) in <class:App>'
	from /home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/gli-2.22.0/lib/gli/command_support.rb:131:in `execute'
	from /home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/gli-2.22.0/lib/gli/app_support.rb:298:in `block in call_command'
	from /home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/gli-2.22.0/lib/gli/app_support.rb:311:in `call_command'
	from /home/cul8er/projects/alet/0.2.0/describe/vendor/bundle/ruby/3.3.0/gems/gli-2.22.0/lib/gli/app_support.rb:85:in `run'
	from ./bin/alet:4:in `<main>'

```

**Comment by tmkw** [comment]
done #118
